### ISSUE TITLE
Update needed for HA 2023.8

### ISSUE THREAD

**Issue by iridris** [bmccluskey/robovac#29]
The beta for HA Core 2023.8 is now released and is displaying a warning for this integration:

The robovac custom integration is using deprecated vacuum feature
This stops working in version 2024.2.0. Please address before upgrading.
The custom integration `robovac` is extending the deprecated base class `VacuumEntity` instead of `StateVacuumEntity`.

Please report it to the author of the `robovac` custom integration.

Once an updated version of `robovac` is available, install it and restart Home Assistant to fix this issue.
![image](https://github.com/bmccluskey/robovac/assets/952387/bbff8bb8-8c3f-4491-8fa5-e4ae2f829dd9)

**Comment by DariukaB** [comment]
same here

**Comment by Redding43** [comment]
Same

**Comment by pem884** [comment]
I'd take a look if I had a moment, but for now, I'll link to the relevant blog for convenience:
[Updated to the Vacuum entity integration](https://developers.home-assistant.io/blog/2023/07/10/vacuum-updates/)

**Comment by morpheus302** [comment]
Same here. Hope we get to use robovac integration in HA soon :)
Thank you for your great work

**Comment by Uwe80469** [comment]
Same in my Installation.

![image](https://github.com/bmccluskey/robovac/assets/78937014/d188729f-5f34-4d44-b676-1993dff41280)


Thank you for your wonderful work.

**Comment by xhemp** [comment]
I have restored my last snapshot and went back to 2023.7 for now.

**Comment by DariukaB** [comment]
> I have restored my last snapshot and went back to 2023.7 for now.

restored it too :) waiting the update for eufy robovac

**Comment by pheijms** [comment]
Same problem here. Waiting for an uopdate.

**Comment by pwcazenave** [comment]
There's a fix available in #31.

**Comment by DariukaB** [comment]
Worked for me 👍

**Comment by michaelmior** [comment]
It should still work for now. This is just a warning that it will stop working with the February update.

**Comment by rokimuc** [comment]
Give it a try with this one https://github.com/CodeFoodPixels/robovac

**Comment by CodeFoodPixels** [comment]
The current implementation passes something unexpected to a class and causes it to raise an exception in the latest version of home assistant, which is why it isn't working.

Given that the maintainer of this integration hasn't been active on GitHub since December 2022, I've forked this repo with a view to maintain it along with anyone else who would like to help.

Fork is here, but happy to consider setting up an org or whatever: https://github.com/CodeFoodPixels/robovac

**Comment by teskanoo** [comment]
I have seen the same error as others and additionally the integration is unable to setup the devices:
```

2023-08-20 15:55:45.094 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.robovac
2023-08-20 15:55:45.123 WARNING (MainThread) [homeassistant.components.vacuum] robovac::RoboVacEntity is extending the deprecated base class VacuumEntity instead of StateVacuumEntity, this is not valid and will be unsupported from Home Assistant 2024.2. Please report it to the author of the 'robovac' custom integration
2023-08-20 15:55:45.174 INFO (MainThread) [homeassistant.components.calendar] Setting up calendar.local_calendar
2023-08-20 15:55:45.178 ERROR (MainThread) [homeassistant.components.vacuum] Error adding entities for domain vacuum with platform robovac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'
2023-08-20 15:55:45.355 INFO (MainThread) [homeassistant.components.button] Setting up button.plex
2023-08-20 15:55:45.357 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'

```

**Comment by pem884** [comment]
> I have seen the same error as others and additionally the integration is unable to setup the devices:
> ```
> 
> 2023-08-20 15:55:45.094 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.robovac
> 2023-08-20 15:55:45.123 WARNING (MainThread) [homeassistant.components.vacuum] robovac::RoboVacEntity is extending the deprecated base class VacuumEntity instead of StateVacuumEntity, this is not valid and will be unsupported from Home Assistant 2024.2. Please report it to the author of the 'robovac' custom integration
> 2023-08-20 15:55:45.174 INFO (MainThread) [homeassistant.components.calendar] Setting up calendar.local_calendar
> 2023-08-20 15:55:45.178 ERROR (MainThread) [homeassistant.components.vacuum] Error adding entities for domain vacuum with platform robovac
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
>     device = dev_reg.async_get(self.hass).async_get_or_create(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'
> 2023-08-20 15:55:45.355 INFO (MainThread) [homeassistant.components.button] Setting up button.plex
> 2023-08-20 15:55:45.357 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
>     device = dev_reg.async_get(self.hass).async_get_or_create(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'access_token'
> 
> ```

Have you tried moving over to using the fork specified in the previous post? If not, please do so. It is working well for me with the fork. Then, if there are any concerns with the fork, it may be appropriate to raise an issue under that fork.
